name: tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Install Poetry
              run: |
                  python -m pip install --upgrade pip
                  pip install poetry
            - name: Install dependencies
              run: |
                  poetry install --with dev
            - name: Run tests
              run: |
                  poetry run pytest
            - name: Upload coverage report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-report
                  path: |
                      ./.coverage
                      ./htmlcov
                  if-no-files-found: ignore
